### ISSUE TITLE
Integrate rln into waku-simulator

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/waku-simulator#4]
- [ ] Modify `waku-publisher`. Check with @richard-ramos how to publish rln messages.
- [ ] Modify `nwaku` to allow publishing messages via the RPC using RLN. 
- [ ] Deploy new contract in sepolia [contract](https://github.com/vacp2p/rln-contract)
- [ ] Ask for set sepolia endpoint.
- [ ] Register memberships using nwaku `--rln-relay-eth-account-private-key`

Tests:
* send messages at rate <1 msg/second. 100 nodes, 10kB size. from only 1 waku-publisher.
* 

Output:
* Grafana dashboards using the metrics that we already have.
* + mem, cpu, bandwidth.
* compare against the benchmark.

**Comment by rymnc** [comment]
Deployed rln-contract for waku-simulator -

```
RLN_CONTRACT_ADDRESS = 0x39558059411112732D73997712B75a865a697330
NETWORK = SEPOLIA
CHAIN_ID = 11155111
```

**Comment by alrevuelta** [comment]
static RLN was already integrated in waku-simulator. https://github.com/waku-org/waku-simulator/issues/17 tracks the integration of onchain RLN. closing.
