### ISSUE TITLE
Collisions due to same nonce

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/waku-simulator#52]
When multiple `nwaku` containers start they all use the same `PRIVATE_KEY` to register its RLN membership into the contract. The problem is that if two (or more) of them do it at the same time, they will broadcast a tx with the same nonce. One of them will get in, and the other one will get rejected.

I see two possible fixes:
* 1) Use a random delay in each nwaku node before registering the membership. So that we avoid collisions with a high change.
* 2) Use a different account per nwaku node, so that we guarantee that no nonce collisions are produced.

Since ii) seems more complex to implement, I would say i) its enough by now.

Requirements:
- [ ] Fix nonce collision problem by implementing a random delay before a `nwaku` node registers its membership.

**Comment by stubbsta** [comment]
I implemented the first option and could not get reliable results. Most of the nodes registered successfully, but never all of them.
I added a random wait with set max value in the run_nwaku script before the step to generate the keystore.
This was tested with docker configured to create 35 nwaku nodes and varying max sleep times, results were as follows:
- 300s sleep -> 30 nodes registered
- 400s sleep -> 33 nodes registered
- 500s sleep -> 34 nodes registered

These results are not acceptable. We require full node registration as fast as possible. Moving on to the second approach.

**Comment by stubbsta** [comment]
Implementing a different account per nwaku node has several requirements.
- We can use the NUM_NWAKU_NODES env variable to configure how many accounts anvil generates at startup.
- It is also possible to have anvil write the addresses and private keys to a file.
- It would be ideal to have a variable with this information that can be used by the nwaku nodes, but environment variables are static outside of the container and not sharable within separate containers. However it is possible to write the file to a shared volume which is accessible by all containers.
- How to get each created node to use a different account? WIP

**Comment by alrevuelta** [comment]
> How to get each created node to use a different account? WIP

can't we use the existing `NODE_INDEX` for this?

**Comment by stubbsta** [comment]
> > How to get each created node to use a different account? WIP
> 
> can't we use the existing `NODE_INDEX` for this?

The NODE_INDEX is the last number of the container IP, and I am not sure how the container IPs are allocated, but it is not in sequence and not confined to the range of the number of nodes:
```
waku-simulator_nwaku_7    | IP: 10.2.0.40 | NODE_INDEX 40
waku-simulator_nwaku_39   | IP: 10.2.0.29 | NODE_INDEX 29
waku-simulator_nwaku_30   | IP: 10.2.0.32 | NODE_INDEX 32
```

I found a different approach where I can obtain the container index from the container name:
waku-simulator_nwaku_**7**

This should work in most cases. In cases where some containers are stopped and new containers are created then the index could be out of the bounds of the list of accounts. But this shouldn't happen unless there someone makes manual changes.

I have a working implementation. I need to first clean up the code a bit and then I'll make the PR

**Comment by alrevuelta** [comment]
> I found a different approach where I can obtain the container index from the container name:

this works for me.
