### ISSUE TITLE
Configure bootstrap node properly

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/waku-simulator#53]
Currently, the bootstrap node has a different configuration than the rest of the `nwaku` nodes. This can cause problems since the bootstrap node may consider invalid messages that are valid for the rest of the network.

I see two possible solutions
* 1) Set the same configuration in the boostrap node than in the rest of nwaku nodes.
* 2) Disable all protocols in the boostrap node, so that its used only for discovery and not for relay and other protocols.

**Comment by stubbsta** [comment]
If the goal is to simplify things then I think solution 2 (ii) is the way to go.
That way we can forget about the bootstrap node, to an extent, and focus on testing the functionality of the nwaku nodes as full service nodes and light clients.
What do you think @alrevuelta ?

**Comment by alrevuelta** [comment]
Makes sense thanks, lets go ahead with 2)
