### ISSUE TITLE
The instance configured with default credentials accessible over the Internet

### ISSUE THREAD

**Issue by 0xM3R** [waku-org/waku-simulator#55]
We received a report, a bug hunter found a login on [http://metal-01.he-eu-hel1.wakusim.misc.status.im:3001/](http://metal-01.he-eu-hel1.wakusim.misc.status.im:3001/) with default credentials `(admin/admin)`

This is not only a bad practice but we might leak sensitive information about our infrastructure. Please change the default passwords additionally consider integrating access with SSO.

**Comment by apentori** [comment]
The port 3001 shouldn't be available for the public, it's a firewall misconfiguration on the host, probably after some debugging:

The desired state : https://github.com/status-im/infra-misc/blob/master/ansible/group_vars/wakusim.yml#L77 (port 3001 open only for docker container).

On the host: 
```bash
 sudo iptables -vnL | grep 3001
    0     0 ACCEPT     tcp  --  !br-8f33de525b1c br-8f33de525b1c  0.0.0.0/0            10.2.0.11            tcp dpt:3001
 167K   15M ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:3001 /* Explorer */
    0     0 ACCEPT     tcp  --  *      *       172.17.0.0/16        0.0.0.0/0            tcp dpt:3001 /* Grafana OAuth */
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:3001 match-set proxy.misc src /* Explorer */
```

Removing the configuration:

```
 167K   15M ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:3001 /* Explorer */
 ```
 
 Grafana is accessible throught the an oauth proxy configured with github waku-org as oidc provider.

**Comment by apentori** [comment]
Updating Grafana default admin password with : 
* https://github.com/status-im/infra-misc/pull/276
* https://github.com/waku-org/waku-simulator/pull/56

**Comment by stubbsta** [comment]
All changes have been merged in Infra and waku-simulator. Thanks for the assistance @apentori and @jakubgs
